spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource



  redis:
    database: 0
    host: 192.168.0.113
    port: 6379
    pool:
      max-active: 10
      max-wait: -1
  jpa:
    database: mysql
    show-sql: true
